# Site settings
title: Sh4dowtech
email: sh4dowtechalajuela@gmail.com
url: https://github.com/Sh4dowtech
description: "'Sh4dowtech' es un Negocio que busca brindar soluciones tecnologicas en diferentes campos de la informatica para poder ayudar a todos aquellos que lo ocupen"
keywords: "Business,Sh4dowtech,Tecnology,Negocio,Tech,Tecnologia"
skills: "Computadoras - Sistemas - Recuperacion de Datos - Hackeo de Consolas - Produccion de Video - Paginas Web"
meta_author: Solano Ramses

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 008FF5 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 100000 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sh4dowtech
  location: Costa Rica

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100088573369613
  - title: github
    url: https://github.com/Sh4dowtech

# Postal address (add as many lines as necessary)
address:
  - line: Del Super Cali 50 Norte 50 Este
  - line: Guacima, Alajuela, Alajuela, 20105

# Credits content
credits: 'Esta es la Pagina Oficial de Sh4dowtech Modificada por <a href="http://github.com/sh4dow18">Sh4dow18</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
